# Generated by Django 2.1.3 on 2019-04-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0004_auto_20190412_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
