# Generated by Django 2.1.3 on 2019-04-13 14:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0005_auto_20190412_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='expiration_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
