# Generated by Django 2.1.3 on 2019-04-13 17:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task_list', '0015_auto_20190413_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
